/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package opencvjavawebcams2;

import org.opencv.core.Core;

/**
 *
 * @author felipe
 */
public class JMainSample2 extends javax.swing.JFrame {
    VideoSample2 Sample;
    /**
     * Creates new form JMainSample2
     */
    public JMainSample2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblVideoTest = new javax.swing.JLabel();
        jBtnStartVideo = new javax.swing.JButton();
        jLblInfoNow = new javax.swing.JLabel();
        jLblFpsNow = new javax.swing.JLabel();
        jLblInfoMax = new javax.swing.JLabel();
        jLblFpsMax = new javax.swing.JLabel();
        jLblInfoMin = new javax.swing.JLabel();
        jLblFpsMin = new javax.swing.JLabel();
        jLblInfoAvg = new javax.swing.JLabel();
        jLblFpsAvg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAMPLE 2 FPS");
        setResizable(false);

        jLblVideoTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVideoTest.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "WebCam", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jBtnStartVideo.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        jBtnStartVideo.setText("START");
        jBtnStartVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStartVideoActionPerformed(evt);
            }
        });

        jLblInfoNow.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLblInfoNow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblInfoNow.setText("FPS NOW");

        jLblFpsNow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFpsNow.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblInfoMax.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLblInfoMax.setText("FPS MAX");

        jLblFpsMax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFpsMax.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblInfoMin.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLblInfoMin.setText("FPS MIN");

        jLblFpsMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFpsMin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblInfoAvg.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLblInfoAvg.setText("FPS AVG");

        jLblFpsAvg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFpsAvg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblInfoNow, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblFpsNow, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblInfoMax)
                        .addGap(27, 27, 27)
                        .addComponent(jLblFpsMax, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblInfoMin)
                        .addGap(18, 18, 18)
                        .addComponent(jLblFpsMin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblInfoAvg)
                        .addGap(18, 18, 18)
                        .addComponent(jLblFpsAvg, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 96, Short.MAX_VALUE))
                    .addComponent(jLblVideoTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnStartVideo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLblFpsAvg, jLblFpsMax, jLblFpsMin, jLblFpsNow});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblVideoTest, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLblInfoNow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblFpsNow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblInfoMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblFpsMax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblInfoMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblFpsMin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblInfoAvg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblFpsAvg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnStartVideo)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnStartVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStartVideoActionPerformed
        // TODO add your handling code here:
        if(Sample == null)
        {
            jBtnStartVideo.setText("STOP");
            Sample = new VideoSample2(jLblVideoTest);
            Sample.SetEnvLabelsInfo(jLblFpsNow, jLblFpsMax, jLblFpsMin, jLblFpsAvg);
            Sample.StartWebCamSample2();
        }
        else
        {
            jBtnStartVideo.setText("START");
            Sample.StopWebCamSample2();
            Sample = null;
        }
    }//GEN-LAST:event_jBtnStartVideoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMainSample2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMainSample2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMainSample2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMainSample2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
                new JMainSample2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnStartVideo;
    private javax.swing.JLabel jLblFpsAvg;
    private javax.swing.JLabel jLblFpsMax;
    private javax.swing.JLabel jLblFpsMin;
    private javax.swing.JLabel jLblFpsNow;
    private javax.swing.JLabel jLblInfoAvg;
    private javax.swing.JLabel jLblInfoMax;
    private javax.swing.JLabel jLblInfoMin;
    private javax.swing.JLabel jLblInfoNow;
    private javax.swing.JLabel jLblVideoTest;
    // End of variables declaration//GEN-END:variables
}
